In [1]:
import pandas as pd

In [5]:
from pandas import Series,DataFrame


# Series

In [6]:
obj=pd.Series([4,7,-5,3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']


-5

In [13]:
obj2['b']

7

In [11]:
obj2['c']

3

In [12]:
obj2['d']

4

In [13]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [14]:

obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [16]:
sdata={'Ohio':35000,'Texas':7100,'Oregon':16000,'Utah':5000}
cdata={'Name','Quentity'}
obj6=pd.Series(sdata)
obj6.coloumns(cdata)

AttributeError: 'Series' object has no attribute 'coloumns'

In [20]:
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [26]:
pd.isnull(obj3)

Ohio      False
Texas     False
Oregon    False
Utah      False
dtype: bool

In [27]:
pd.notnull(obj3)

Ohio      True
Texas     True
Oregon    True
Utah      True
dtype: bool

In [28]:
obj3.isnull()

Ohio      False
Texas     False
Oregon    False
Utah      False
dtype: bool

In [29]:
obj3

Ohio      35000
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [34]:
obj3.name='Population'
obj3.index.name='state'
obj3

state
Ohio      35000
Texas      7100
Oregon    16000
Utah       5000
Name: Population, dtype: int64

In [35]:
obj.index=['Bob','steve','Jeff','Ryan']
obj

Bob      4
steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [36]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
     'Year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)

In [37]:
frame

state  Year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
frame.head()

state  Year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [42]:
pd.DataFrame(data,columns=['state','year','pop'])


state year  pop
0    Ohio  NaN  1.5
1    Ohio  NaN  1.7
2    Ohio  NaN  3.6
3  Nevada  NaN  2.4
4  Nevada  NaN  2.9
5  Nevada  NaN  3.2

In [45]:
pd.DataFrame(data,columns=['state','pop'])

state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.4
4  Nevada  2.9
5  Nevada  3.2

In [54]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['ones','two','three','four','five','six'])

In [48]:
frame2

year   state  pop debt
ones   NaN    Ohio  1.5  NaN
two    NaN    Ohio  1.7  NaN
three  NaN    Ohio  3.6  NaN
four   NaN  Nevada  2.4  NaN
five   NaN  Nevada  2.9  NaN
six    NaN  Nevada  3.2  NaN

In [49]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [55]:
frame2['state']

ones       Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [57]:
frame2.state


ones       Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [58]:
frame2.year

ones     NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: year, dtype: object

In [59]:
frame2.loc['three']

year      NaN
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [60]:
frame2['debt']=16.5
frame2

year   state  pop  debt
ones   NaN    Ohio  1.5  16.5
two    NaN    Ohio  1.7  16.5
three  NaN    Ohio  3.6  16.5
four   NaN  Nevada  2.4  16.5
five   NaN  Nevada  2.9  16.5
six    NaN  Nevada  3.2  16.5

In [68]:
frame2['debt']=np.arange(6.)
frame2['year']=2001

In [69]:
frame2

year   state  pop  debt
ones   2001    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2001    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2001  Nevada  2.9   4.0
six    2001  Nevada  3.2   5.0

In [70]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt']=val
frame2

year   state  pop  debt
ones   2001    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2001    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2001  Nevada  3.2   NaN

In [71]:
frame2

year   state  pop  debt
ones   2001    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2001    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2001  Nevada  3.2   NaN

In [75]:
frame2['eastern'] = frame2.state=='Ohio'
frame2.columns


Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [76]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [77]:
pop ={'Nevada':{2001:2.4,2002:2.9},
     'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [78]:
frame2

year   state  pop  debt
ones   2001    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2001    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2001  Nevada  3.2   NaN

In [79]:
frame3=pd.DataFrame(pop)

In [80]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [81]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [82]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [83]:
pdata={'Ohio':frame3['Ohio'][:-1],
      'Nevada':frame3['Nevada'][:2]}

In [84]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [87]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
frame3.values


array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [89]:
frame2.values

array([[2001, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2001, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2001, 'Nevada', 2.9, -1.7],
       [2001, 'Nevada', 3.2, nan]], dtype=object)

# index

# Object

In [90]:
obj=pd.Series(range(3),index=['a','b','c'])

In [91]:
index=obj.index

In [92]:
index

Index(['a', 'b', 'c'], dtype='object')

In [94]:
index[1:]


Index(['b', 'c'], dtype='object')

In [98]:
lables=pd.Index(np.arange(3))

In [99]:
lables

Int64Index([0, 1, 2], dtype='int64')

In [100]:
obj2=pd.Series([1.5,-2.5,0],index=lables)

In [101]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [103]:
obj2.index is lables

True

In [104]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [105]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [106]:
'Ohio' in frame3.columns

True

In [108]:
2003 in frame3.index

False

In [109]:
dup_labels=pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Essential Functionality

# Reindexing

In [110]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [111]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [112]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [114]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [119]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
index=['a','c','d'],
columns=['Ohio','Texas','colifornia'])

In [116]:
frame

Ohio  Texas  colifornia
a     0      1           2
c     3      4           5
d     6      7           8

In [117]:
frame2

year   state  pop  debt
ones   2001    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2001    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2001  Nevada  3.2   NaN

In [123]:
states=['Texas','Utah','colifornia']
frame.reindex(columns=states)

Texas  Utah  colifornia
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [127]:
frame.loc[['a','b','c','d'],state]

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  colifornia
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

# Droping Entering From An Axis

In [128]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [129]:
new_obj=obj.drop('c')
new_obj


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [131]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [133]:
data=pd.DataFrame(np.arange(16).reshape((4,4))),index=['Ohio','Colorado','Utah','NewYork'],
                 columns=['one','two','three','four'])
data

IndentationError: unexpected indent (<ipython-input-133-faee3c4c760e>, line 2)